# Generated by Django 3.1.2 on 2021-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210131_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='state',
            new_name='interview',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stage',
        ),
        migrations.AddField(
            model_name='application',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.BooleanField(default=False),
        ),
    ]
