# Generated by Django 3.1.2 on 2021-02-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210203_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='result',
            field=models.CharField(choices=[('NO', 'None'), ('AC', 'Accepted'), ('RE', 'Rejected')], default='NO', max_length=2),
        ),
    ]
