# Generated by Django 3.1.2 on 2021-02-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210203_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='link',
        ),
    ]
